package com.fiap.healthmed.domain.errors

enum class ErrorType {
    DOCTOR_ALREADY_EXISTS,
    DOCTOR_NOT_FOUND,

    PATIENT_ALREADY_EXISTS,
    PATIENT_NOT_FOUND,

    IMCOMPATIBLE_SCHEDULE,
    UNAVAILABLE_TIME,
    APPOINTMENT_NOT_FOUND,

    NO_MEDICAL_RECORDS,

    UNEXPECTED_ERROR,
}
