package com.fiap.healthmed.domain.errors

enum class ErrorType {
    APPOINTMENT_NOT_FOUND,
    DOCTOR_NOT_FOUND,
    DOCKER_ALREADY_EXISTS,
    PATIENT_ALREADY_EXISTS,
    PATIENT_NOT_FOUND,

    UNEXPECTED_ERROR,
    IMCOMPATIBLE_SCHEDULE,
    UNAVAILABLE_TIME,
}
