apiVersion: apps/v1
kind: Deployment
metadata:
    name: healthmed-deployment
    namespace: healthmed
    labels:
        app: healthmed
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app: healthmed
    template:
        metadata:
            namespace: healthmed
            labels:
                app: healthmed
        spec:
            serviceAccountName: healthmed-service-account
            volumes:
                - name: secrets-store-inline
                  csi:
                      driver: secrets-store.csi.k8s.io
                      readOnly: true
                      volumeAttributes:
                          secretProviderClass: healthmed-aws-secrets
            containers:
                - name: healthmed
                  image: 202062340677.dkr.ecr.us-east-1.amazonaws.com/fiap-3soat-g15-healthmed:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          cpu: "100m"
                      limits:
                          cpu: "200m"
                  volumeMounts:
                      - name: secrets-store-inline
                        mountPath: "/mnt/secrets-store"
                        readOnly: true
                  livenessProbe:
                      httpGet:
                          path: /actuator/health
                          port: 8080
                      periodSeconds: 30
                      failureThreshold: 10
                      initialDelaySeconds: 20
                      timeoutSeconds: 5
                  readinessProbe:
                      httpGet:
                          path: /actuator/health
                          port: 8080
                      periodSeconds: 30
                      failureThreshold: 10
                      initialDelaySeconds: 20
                      timeoutSeconds: 5
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        value: live
                      - name: DB_ENDPOINT
                        valueFrom:
                            secretKeyRef:
                                name: healthmed-db-secrets
                                key: endpoint
                      - name: DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: healthmed-db-secrets
                                key: name
                      - name: DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: healthmed-db-secrets
                                key: username
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: healthmed-db-secrets
                                key: password
                      - name: ADMIN_ACCESS_TOKEN
                        value: token
