apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: healthmed-hpa
    namespace: healthmed
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: healthmed-deployment
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
